// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"github.com/fiqriardiansyah/shopping-api-golang/internal/module/product/repository"
	"github.com/fiqriardiansyah/shopping-api-golang/internal/module/product/usecase"
	"github.com/go-playground/validator/v10"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeProductHandler(db *gorm.DB, validate *validator.Validate) *ProductController {
	productRepository := repository.NewProductRepository()
	productUseCase := usecase.NewProductUseCase(productRepository, db)
	productController := NewProductController(productUseCase, validate)
	return productController
}
