// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package order

import (
	"github.com/fiqriardiansyah/shopping-api-golang/internal/module/order/repository"
	"github.com/fiqriardiansyah/shopping-api-golang/internal/module/order/usecase"
	"github.com/go-playground/validator/v10"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeOrderHandler(db *gorm.DB, validate *validator.Validate) *OrderController {
	orderRepository := repository.NewOrderRepository(db)
	orderUseCase := usecase.NewOrderUseCase(orderRepository, db)
	orderController := NewOrderController(orderUseCase)
	return orderController
}
