// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/fiqriardiansyah/shopping-api-golang/internal/helper"
	"github.com/fiqriardiansyah/shopping-api-golang/internal/module/user/usecase"
)

// Injectors from wire.go:

func InitializeUserHandler(grpcClient *helper.GrpcClient) *UserController {
	userUseCase := usecase.NewUserUseCase(grpcClient)
	userController := NewUserController(grpcClient, userUseCase)
	return userController
}
